### ISSUE TITLE
Please Update For Mint 18

### ISSUE THREAD

**Issue by ghost** [jsayol/dark-mint-plymouth-theme#1]
This doesn't work for Mint 18, need an update please, if you're still working on this.

Thanks

**Comment by jsayol** [comment]
Hi @Geyup, sorry it took me so long to reply. I'm quite busy at the moment, plus I don't use Linux Mint anymore, so I won't be able to tackle this.

Feel free to give it a go yourself if you feel like it. Pull Requests are always welcome :)

**Comment by ghost** [comment]
No problem...

**Comment by jsayol** [comment]
Hey @Geyup, the theme has just been updated to Mint 18 thanks to @TheLastOperator! Check the README.

**Comment by ghost** [comment]
Thanks
